In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [2]:
text = """경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

In [3]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 12


In [4]:
print(tokenizer.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [5]:
sequences = list()
for line in text.split('\n'): # 줄바꿈 문자를 기준으로 문장 토큰화
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수: %d' % len(sequences))

학습에 사용할 샘플의 개수: 11


In [6]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [7]:
max_len = max(len(l) for l in sequences) # 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 6


In [8]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')

In [9]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [10]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [11]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [12]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [13]:
y = to_categorical(y, num_classes=vocab_size)

In [14]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [15]:
embedding_dim = 10
hidden_units = 32

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 1s - loss: 2.4919 - accuracy: 0.0000e+00 - 1s/epoch - 1s/step
Epoch 2/200
1/1 - 0s - loss: 2.4776 - accuracy: 0.0909 - 9ms/epoch - 9ms/step
Epoch 3/200
1/1 - 0s - loss: 2.4633 - accuracy: 0.1818 - 10ms/epoch - 10ms/step
Epoch 4/200
1/1 - 0s - loss: 2.4489 - accuracy: 0.1818 - 18ms/epoch - 18ms/step
Epoch 5/200
1/1 - 0s - loss: 2.4343 - accuracy: 0.3636 - 9ms/epoch - 9ms/step
Epoch 6/200
1/1 - 0s - loss: 2.4194 - accuracy: 0.4545 - 7ms/epoch - 7ms/step
Epoch 7/200
1/1 - 0s - loss: 2.4040 - accuracy: 0.5455 - 10ms/epoch - 10ms/step
Epoch 8/200
1/1 - 0s - loss: 2.3881 - accuracy: 0.5455 - 9ms/epoch - 9ms/step
Epoch 9/200
1/1 - 0s - loss: 2.3715 - accuracy: 0.5455 - 8ms/epoch - 8ms/step
Epoch 10/200
1/1 - 0s - loss: 2.3541 - accuracy: 0.5455 - 10ms/epoch - 10ms/step
Epoch 11/200
1/1 - 0s - loss: 2.3359 - accuracy: 0.5455 - 8ms/epoch - 8ms/step
Epoch 12/200
1/1 - 0s - loss: 2.3168 - accuracy: 0.4545 - 8ms/epoch - 8ms/step
Epoch 13/200
1/1 - 0s - loss: 2.2967 - accuracy: 0.

Epoch 104/200
1/1 - 0s - loss: 0.6774 - accuracy: 0.7273 - 9ms/epoch - 9ms/step
Epoch 105/200
1/1 - 0s - loss: 0.6661 - accuracy: 0.7273 - 10ms/epoch - 10ms/step
Epoch 106/200
1/1 - 0s - loss: 0.6550 - accuracy: 0.7273 - 8ms/epoch - 8ms/step
Epoch 107/200
1/1 - 0s - loss: 0.6442 - accuracy: 0.7273 - 10ms/epoch - 10ms/step
Epoch 108/200
1/1 - 0s - loss: 0.6335 - accuracy: 0.8182 - 11ms/epoch - 11ms/step
Epoch 109/200
1/1 - 0s - loss: 0.6230 - accuracy: 0.8182 - 9ms/epoch - 9ms/step
Epoch 110/200
1/1 - 0s - loss: 0.6127 - accuracy: 0.8182 - 10ms/epoch - 10ms/step
Epoch 111/200
1/1 - 0s - loss: 0.6025 - accuracy: 0.8182 - 10ms/epoch - 10ms/step
Epoch 112/200
1/1 - 0s - loss: 0.5926 - accuracy: 0.8182 - 9ms/epoch - 9ms/step
Epoch 113/200
1/1 - 0s - loss: 0.5828 - accuracy: 0.8182 - 10ms/epoch - 10ms/step
Epoch 114/200
1/1 - 0s - loss: 0.5731 - accuracy: 0.8182 - 8ms/epoch - 8ms/step
Epoch 115/200
1/1 - 0s - loss: 0.5636 - accuracy: 0.8182 - 9ms/epoch - 9ms/step
Epoch 116/200
1/1 - 0s - los

In [16]:
def sentence_generation(model, tokenizer, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word
    sentence = ''

    # n번 반복
    for _ in range(n):
        # 현재 단어에 대한 정수 인코딩과 패딩
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis=1)

        for word, index in tokenizer.word_index.items(): 
            # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면 break
            if index == result:
                break

        # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        current_word = current_word + ' '  + word

        # 예측 단어를 문장에 저장
        sentence = sentence + ' ' + word

    sentence = init_word + sentence
    return sentence

In [17]:
print(sentence_generation(model, tokenizer, '경마장의', 4))

경마장의 말이 말이 있는 말이


In [18]:
print(sentence_generation(model, tokenizer, '그의', 2))

그의 말이 법이다


In [19]:
print(sentence_generation(model, tokenizer, '가는', 5))

가는 말이 고와야 오는 말이 곱다


In [20]:
print(sentence_generation(model, tokenizer, '경마장에', 4))

경마장에 있는 말이 뛰고 있다
